### ISSUE TITLE
Theres no way for me to download and try your app

### ISSUE THREAD

**Issue by aliar97** [null-uw/Beacon#17]
I dont see any way for me to download your app, I'm on an android device. This is definitely a major issue. I should be able to get a way to quickly access your app.

**Comment by matthewkli97** [comment]
Please refer to the download instructions for android located on our release documentation: https://github.com/null-uw/Beacon/blob/master/REL.md

Closing this issue as a **non-issue**. The author appears to not have seen the download instructions at the bottom of our release documentation. We've removed the miscellaneous details in the release documentation in commit 9051a9a

**Comment by matthewkli97** [comment]
Closing issue since release documentation outlines a quick way to access our app, especially for android.
